import {
  Award,
  BrickWall,
  Building2,
  CircleCheck,
  Clock,
  Cog,
  Compass,
  Construction,
  Factory,
  Forklift,
  Gauge,
  Hammer,
  Handshake,
  HardHat,
  House,
  Landmark,
  Layers,
  Leaf,
  Map as MapIcon,
  Package,
  Repeat,
  Ruler,
  ShieldCheck,
  Truck,
  Users,
  Warehouse,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

/** Icons an admin can pick for services and "Kenapa BBP" items. */
export const ICONS: Record<string, { icon: LucideIcon; label: string }> = {
  "building-2": { icon: Building2, label: "Gedung" },
  factory: { icon: Factory, label: "Pabrik" },
  warehouse: { icon: Warehouse, label: "Gudang" },
  layers: { icon: Layers, label: "Lapisan / atap" },
  zap: { icon: Zap, label: "Listrik" },
  map: { icon: MapIcon, label: "Peta / lahan" },
  package: { icon: Package, label: "Pengadaan" },
  truck: { icon: Truck, label: "Truk / alat" },
  forklift: { icon: Forklift, label: "Forklift" },
  construction: { icon: Construction, label: "Konstruksi" },
  "hard-hat": { icon: HardHat, label: "Helm K3" },
  "shield-check": { icon: ShieldCheck, label: "Keamanan / legal" },
  award: { icon: Award, label: "Penghargaan" },
  "circle-check": { icon: CircleCheck, label: "Centang" },
  ruler: { icon: Ruler, label: "Penggaris" },
  compass: { icon: Compass, label: "Desain" },
  wrench: { icon: Wrench, label: "Kunci" },
  hammer: { icon: Hammer, label: "Palu" },
  cog: { icon: Cog, label: "Mekanikal" },
  "brick-wall": { icon: BrickWall, label: "Dinding" },
  house: { icon: House, label: "Hunian" },
  landmark: { icon: Landmark, label: "Instansi" },
  users: { icon: Users, label: "Tim" },
  handshake: { icon: Handshake, label: "Kerja sama" },
  repeat: { icon: Repeat, label: "Berulang" },
  clock: { icon: Clock, label: "Waktu" },
  gauge: { icon: Gauge, label: "Kapasitas" },
  leaf: { icon: Leaf, label: "Lingkungan" },
};

export const ICON_OPTIONS = Object.entries(ICONS).map(([id, v]) => ({ id, label: v.label }));

export function iconFor(id: string | undefined | null): LucideIcon {
  return (id && ICONS[id]?.icon) || Building2;
}
